version: "3.7"

services:
  nginx:
    image: nginx
    volumes:
      - D:/wwwroot:/usr/share/nginx/html
      - ./nginx/conf/conf.d:/etc/nginx/conf.d
      - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/log:/etc/log/nginx
    ports:
      - 80:80
    environment:
      - TZ=Asia/Shanghai
    links:
      - php-fpm
    container_name: dc-nginx
    tty : true

  php-fpm:
    build: ./php-fpm
    links:
      - mysql
      - redis
      - memcached
    ports:
      - 9000:9000
    volumes:
      - D:/wwwroot:/usr/share/nginx/html
      - ./php-fpm/conf/php.ini:/usr/local/etc/php/php.ini
      - ./php-fpm/log:/etc/log/php
    container_name: dc-php
    tty : true

  mysql:
    image: mysql:5.7
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - ./mysql/conf/my.cnf:/etc/mysql/my.cnf
    container_name: dc-mysql
    tty : true

  redis:
    image: redis
    command: redis-server --requirepass root
    ports:
      - 6379:6379
    volumes:
      - ./redis/:/data
    container_name: dc-redis
    tty : true

  memcached:
    image: memcached
    ports:
      - 11211:11211
    container_name: dc-memcached
    tty : true
    
  node:
    build: ./node
    ports:
      # 如果8080被占用就换一个
      - 8080:8080
    volumes:
      # 工作目录与项目目录统一
      - D:/wwwroot:/usr/share/nginx/html
    tty : true
    environment:
      # windows环境下一定要进行此配置，否则无法进行热重载
      - CHOKIDAR_USEPOLLING=true
    container_name: dc-node